{% set name = "pytest-aio" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa72e6ca4672b7f5a08ce44e7c6254dca988d3d578bf0c9485a47c3bff393ac1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pytest
  run_constrained:
    - curio *
    - trio *
    - uvloop *

test:
  imports:
    - pytest_aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klen/pytest-aio
  summary: Pytest plugin for testing async python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
