{% set name = "pytest-aio" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 97dcbc1c5ac991705f32bb2cf72f9ba94a8889fd0295d29ed4d7252b3e158684

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytest

test:
  imports:
    - pytest_aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klen/pytest-aio
  summary: Pytest plugin for testing async python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
