{% set python_min = "3.10.0" %}
{% set name = "pytest-aio" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c8ceb6a85930c1720e52b485f1daca9088b37197cca631bc4f589f1b0462a7cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pytest
  run_constrained:
    - curio *
    - trio *
    - uvloop *

test:
  imports:
    - pytest_aio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klen/pytest-aio
  summary: Pytest plugin for testing async python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
